name: Release

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: create_release
      name: Create Release
      uses: toolmantim/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "Release draft need to be published :${{ steps.create_release.outputs.html_url }}"
