name: VLang build workflow test

on:
  push:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Set up VLang version master
      uses: ./
      with:
        v-version: master
      id: v
